### ISSUE TITLE
eval_DMBP_mask & eval_baseline_mask files are missing

### ISSUE THREAD

**Issue by jonathanbrady88** [zhyang2226/DMBP#1]
Thank you for open-sourcing your work, and congratulations on your novel and inspiring contributions! I have found your project incredibly valuable.
I noticed that the files eval_baseline_mask.py and eval_DMBP_mask.py are currently missing from the repository. If possible, could you kindly upload these files?

**Comment by zhyang2226** [comment]
Apologize for the inconvenience caused by the missing files, I have uploaded the “eval_baseline_mask.py” and “eval_DMBP_mask.py” for your reference.

**Comment by jonathanbrady88** [comment]
Thank you very much, and congratulations again!
